name: Cross build U-Boot for the ASUS Transformer device family

on:
  push:
#    branches: [ "master" ]
  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tecolicom/actions-use-apt-tools@v1.6
      with:
        tools: libgnutls28-dev
    - uses: carlosperate/arm-none-eabi-gcc-action@v1.10.1
      with:
        path-env-var: ARM_NONE_EABI_GCC_PATH
    - name: Set CROSS_COMPILE environment variable
      run: echo "CROSS_COMPILE=$(echo "$ARM_NONE_EABI_GCC_PATH/arm-none-eabi-")" >> $GITHUB_ENV
    - name: Configure and Build
      run: |
        make transformer_t30_defconfig
        make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: u-boot-tegra3
          path: u-boot-dtb-tegra.bin
